Update  backend ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,27 +2,46 @@ name: CI
 on: [push, pull_request]
 jobs:
   docker:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
       - run: docker build -t gcr.io/cipherly/cipherly .
   cargo:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
     defaults:
       run:
         working-directory: ./backend
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
-      - uses: actions-rs/toolchain@v1
+      - name: Configure rust version
+        id: rust-version
+        run: |
+          VERSION=$(cat ../rust-toolchain.toml| sed -rn 's/^channel = "([0-9]+\.[0-9]+\.[0-9]+)"/\1/p')
+          if [ -z "${VERSION}" ]; then
+            echo "Version not found in rust-toolchain.toml"
+            exit 1
+          fi
+          echo VERSION=$VERSION >> "$GITHUB_OUTPUT"
+      - name: Setup Rust
+        uses: dtolnay/rust-toolchain@b3b07ba8b418998c39fb20f53e8b695cdcc8de1b # master
         with:
-          toolchain: stable
-          override: true
-      - run: rm -f static && mkdir static
-      - run: cargo test
-      - run: cargo clippy -- -D warnings
-      - run: cargo fmt -- --check
+          toolchain: ${{ steps.rust-version.outputs.VERSION }}
+          components: rustfmt,clippy
+      - name: Rust build cache
+        uses: Swatinem/rust-cache@98c8021b550208e191a6a3145459bfc9fb29c4c0 # v2.8.0
+        with:
+          workspaces: "./ -> target"
+          shared-key: "backend-build"
+      - name: Make static dir
+        run: rm -f static && mkdir static
+      - name: Run cargo test
+        run: cargo test
+      - name: Run cargo clippy
+        run: cargo clippy --all-targets --all-features -- -D warnings
+      - name: Run cargo fmt check
+        run: cargo fmt --all -- --check
   pnpm:
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-24.04
     defaults:
       run:
         working-directory: ./frontend
